name: Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      run: |
        mkdir python
        cd python
        curl https://www.python.org/ftp/python/3.8.5/python-3.8.5-embed-amd64.zip -o python-3.8.5-embed-amd64.zip
        tar.exe -x -f python-3.8.5-embed-amd64.zip
    - name: Install pip
      run: |
        cd python
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        .\python get-pip.py
    - name: Python overrides
      run: |
        copy .\distribution_files\python38._pth .\python\

